name: CI_CD_pipeline
 
on:
  push:
    branches: [ master ]
 
jobs:
 
  build:
    runs-on: self-hosted
 
    steps:
 
    - name: Checkout Code
      uses: actions/checkout@v4
 
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker Image
      run: docker build -t prabhatkumar1991/devops-app:${{ github.run_number }} .
 
    - name: Push Docker Image
      run: docker push prabhatkumar1991/devops-app:${{ github.run_number }}

  test:
    needs: build
    runs-on: self-hosted
 
    steps:
 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: testing
      run: echo "testing successful"
 
  deploy:
    needs: test
    runs-on: self-hosted
 
    steps:
 
    - name: Checkout Code
      uses: actions/checkout@v4
 
    - name: Terraform Init
      working-directory: infra
      run: terraform init
 
    - name: terraform validate
      working-directory: infra
      run: terraform validate
 
    - name: Terraform Plan
      working-directory: infra
      run: terraform plan -var="image_tag=${{ github.run_number }}"
 
    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve -var="image_tag=${{ github.run_number }}"
 
    - name: Verify Deployment  
      run: kubectl get pods -o wide
